LPManagement.UI/Controllers/LPManagementController.cs
using LPManagement.BusinessLogic;
using LPManagement.Common.Enums;
using LPManagement.UI.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LPManagement.UI.Controllers
{
    /// <summary>
    /// LaunchPad management controller.
    /// </summary>
    public class LPManagementController : Controller
    {
        #region Action methods
        #region GET
        /// <summary>
        /// Index action method
        /// </summary>
        /// <returns>Home view.</returns>
        public ActionResult Index()
        {
            //var userDetails = Session["userDetails"] as User;
            //if (userDetails == null)
            //{
            //    return RedirectToAction("Index", "Account");
            //}

            return View();
        }

        /// <summary>
        /// Upload file action method
        /// </summary>
        /// <returns>View to upload file.</returns>
        [HttpGet]
        public ActionResult UploadFile()
        {
            return View();
        }

        /// <summary>
        /// Filters LaunchPad details based on filter criteria.
        /// </summary>
        /// <param name="location">Location</param>
        /// <param name="quarter">Quarter</param>
        /// <param name="status">Status</param>
        /// <param name="financialYear">Financial year</param>
        /// <param name="practice">Practice.</param>
        /// <returns>Dashoboard view</returns>
        [HttpGet]
        public ActionResult Dashboard(Location location = Location.All, Status status = Status.All, int financialYear = 2017, string practice = "All")
        {
            //var userDetails = Session["userDetails"] as User;
            //if (userDetails == null)
            //{
            //    return RedirectToAction("Index", "Account");
            //}           

            var launchPadDetailsModel = GetLaunchPadDetails(location, status, financialYear, practice);
            return View(launchPadDetailsModel);
        }

        /// <summary>
        /// Shows launch pad detail.
        /// </summary>
        /// <param name="location">Location</param>
        /// <param name="quarter">Quarter</param>
        /// <param name="status">Status</param>
        /// <param name="financialYear">Financial year</param>
        /// <param name="practice">Practice.</param>
        /// <returns>Dashboard content view</returns>
        [HttpGet]
        public ActionResult DashboardContent(Location location = Location.All, Status status = Status.All, int financialYear = 2017, string practice = "All")
        {
            var launchPadDetailsModel = GetLaunchPadDetails(location, status, financialYear, practice);
            return PartialView(launchPadDetailsModel);
        }

        /// <summary>
        /// Shows launch pad detail for a given launch pad code.
        /// </summary>
        /// <returns>ActionResult</returns>
        public ActionResult DashboardSummary(string launchPadCode)
        {
            var lPManagementBusinessLogic = new LPManagementBusinessLogic();
            var launchPadSummary = lPManagementBusinessLogic.GetLaunchPadDetailsByLaunchPadCode(launchPadCode);
            var launchPadSummaryModel = new LaunchPadSummaryModel()
            {
                LaunchPadCode = launchPadSummary.LaunchPadCode,
                Status = launchPadSummary.Status,
                TotalNoOfLPCount = launchPadSummary.TotalNoOfLPCount,
                OverallScoreAbove70PercentCount = launchPadSummary.OverallScoreAbove70PercentCount,
                OverallScore60To70PercentCount = launchPadSummary.OverallScore60To70PercentCount,
                OverallScoreBelow60PercentCount = launchPadSummary.OverallScoreBelow60PercentCount
            };

            return PartialView(launchPadSummaryModel);
        }
        #endregion

        #region POST
        /// <summary>
        /// Uploads data file.
        /// </summary>
        /// <param name="file">File to upload</param>
        /// <returns>ActionResult</returns>
        [HttpPost]
        public ActionResult UploadFile(HttpPostedFileBase file)
        {
            try
            {
                if (file.ContentLength > 0)
                {
                    string fileName = Path.GetFileName(file.FileName);
                    string path = Path.Combine(Server.MapPath("~/UploadedFiles"), fileName);
                    file.SaveAs(path);
                    var lPManagementBusinessLogic = new LPManagementBusinessLogic();
                    lPManagementBusinessLogic.ProcessFile(path);
                }
                ViewBag.Message = "File Uploaded Successfully!!";
                return View();
            }
            catch
            {
                ViewBag.Message = "File upload failed!!";
                return View();
            }
        } 
        #endregion
        #endregion

        #region Private methods
        private List<LaunchPadDetailsModel> GetLaunchPadDetails(Location location, Status status, int financialYear, string practice)
        {
            var lPManagementBusinessLogic = new LPManagementBusinessLogic();
            var launchPadDetails = lPManagementBusinessLogic.GetLauchPadDetails(location, Quarter.All, status, financialYear, practice).ToList();
            var launchPadDetailsModel = launchPadDetails.Select(x => new LaunchPadDetailsModel()
            {
                LaunchPadCode = x.LaunchPadCode,
                Location = x.Location,
                FinancialYear = x.FinancialYear,
            }).ToList();

            var locations = Enum.GetValues(typeof(Location)).Cast<Location>().ToList();
            var locationModels = locations.Select(x => new SelectListItem
            {
                Text = x.ToString(),
                Value = x.ToString(),
                Selected = (x == Location.All)
            });
            ViewBag.Locations = locationModels;

            var statusList = Enum.GetValues(typeof(Status)).Cast<Status>().ToList();
            var statusModels = statusList.Select(x => new SelectListItem
            {
                Text = x.ToString(),
                Value = x.ToString(),
                Selected = (x == Status.All)
            });
            ViewBag.Status = statusModels;

            var financialYearList = new List<int>() { 2012, 2013, 2014, 2015, 2016, 2017, 2018 };
            var financialYearModels = financialYearList.Select(x => new SelectListItem
            {
                Text = x.ToString(),
                Value = x.ToString(),
                Selected = (x == DateTime.Today.Year)
            });
            ViewBag.FinancialYear = financialYearModels;

            var practiceList = new List<string>() { "All", "Core", "Core-Citi", "EIM", "QA" };
            var practiceModels = practiceList.Select(x => new SelectListItem
            {
                Text = x.ToString(),
                Value = x.ToString(),
                Selected = (x == "All")
            });
            ViewBag.Practice = practiceModels;

            return launchPadDetailsModel;
        } 
        #endregion
    }
}

LPManagement.UI/Views/LPManagement/Dashboard.cshtml
@model List<LPManagement.UI.Models.LaunchPadDetailsModel>

<section>
    <div class="container-fluid">
        <div class="col-md-3 pull-left">
            <div class="row">
                @Html.Label("Location")
                @Html.DropDownList("locations", ViewBag.Locations as SelectList, new { id = "location", onchange = "getLPDetails()" })
            </div>

            <div class="row">
                @Html.Label("Status")
                @Html.DropDownList("status", ViewBag.Status as SelectList, new { id = "status", onchange = "getLPDetails()" })
            </div>

            <div class="row">
                @Html.Label("Finanicial year")
                @Html.DropDownList("financialYear", ViewBag.FinancialYear as SelectList, new { id = "financialYear", onchange = "getLPDetails()" })
            </div>

            <div class="row">
                @Html.Label("Practice")
                @Html.DropDownList("practice", ViewBag.Practice as SelectList, new { id = "practice", onchange = "getLPDetails()" })
            </div>
        </div>
        <div class="col-md-9">
            @Html.Partial("DashboardContent", Model)
        </div>
    </div>
</section>

<script type="text/javascript">

    function getLPDetails() {
        var location = $("#location").val();
        var status = $("#status").val();
        var financialYear = $("#financialYear").val();
        var practice = $("#practice").val();
        $.ajax
        ({
            url: '/LPManagement/DashboardContent',
            type: 'GET',
            data: { "location": location, "status": status, "financialYear": financialYear, "practice": practice },
            success: function (result) {
                $('.table').html("");
                $('.table').html(result);
            },
            error: function () {
                alert("Server error! Please try after sometime...");
            },
        });
    }
</script>

LPManagement.UI/Views/LPManagement/DashboardContent.cshtml
@{
    WebGrid grid = new WebGrid(null);
    grid.Bind(Model, autoSortAndPage: true);
}


@grid.GetHtml(tableStyle: "table table-bordered",
             mode: WebGridPagerModes.All,
                columns: grid.Columns(
                grid.Column(nameof(LPManagement.UI.Models.LaunchPadDetailsModel.LaunchPadCode), "Launch Pad Code"),
                grid.Column(nameof(LPManagement.UI.Models.LaunchPadDetailsModel.Location), "Location"),
                grid.Column(nameof(LPManagement.UI.Models.LaunchPadDetailsModel.FinancialYear), "Financial Year"),
                grid.Column("Summary", header: null, format: @<text>@item.GetSelectLink("Summary")</text>)
            ))

@if (grid.HasSelection)
{
    @Html.Partial("DashboardSummary");
}

<script type="text/javascript">

    function getLPSummaryDetails() {
        $.ajax
        ({
            url: '/LPManagement/DashboardSummary',
            type: 'GET',
            data: { "launchPadCode": launchPadCode },
            success: function (result) {
                alert(result);
            },
            error: function () {
                alert("Server error! Please try after sometime...");
            },
        });
    }
</script>

LPManagement.UI/Views/LPManagement/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<h2></h2>

<section>
    <button class="btn btn-primary" name="btnDashboard" onclick="location.href='@Url.Action("Dashboard", "LPManagement")'">Dashboard</button>
    <button class="btn btn-success" name="btnUploadFile" onclick="location.href='@Url.Action("UploadFile", "LPManagement")'">Upload File</button>
</section>

LPManagement.UI/Views/LPManagement/UploadFile.cshtml
@{
    ViewBag.Title = "Upload file";
}

<h2>Upload excel</h2>

@using (Html.BeginForm("UploadFile", "LPManagement", FormMethod.Post, new { enctype = "multipart/form-data" }))
{

    <div>
        @Html.TextBox("file", "", new { type = "file", accept = ".xls, .xlsx" }) <br />

        <input type="submit" value="Upload" />

        @ViewBag.Message

    </div>
}
 